apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic
  labels:
    app: logic
spec:
  selector:
     matchLabels:
       app: logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
        - image: emreshome/k8-demo-logic
          imagePullPolicy: Always
          name: logic
          ports:
            - containerPort: 5000