apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: webapp
spec:
  selector:                                               # 2
    matchLabels:
      app: fe                                    
  replicas: 2                                             # 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 4
    rollingUpdate: 
      maxUnavailable: 1                                   # 5
      maxSurge: 1                                         # 6
  template:                                               # 7
    metadata:
      labels:
        app: fe                                           # 8
    spec:
      containers:
        - image: emreshome/k8-demo-fe
          imagePullPolicy: Always                         # 9
          name: webapp
          ports:
            - containerPort: 8080
