apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: webapp-2                                    # 2
  labels:
    app: fe
spec:                                                # 3
  containers:
    - image: emreshome/k8-demo-fe                    # 4
      name: web-app                                 # 5
      ports:
        - containerPort: 8080                          # 6
